### ISSUE TITLE
erj-nc repo

### ISSUE THREAD

**Issue by rootsmusic** [nonpartisan-redistricting-datahub/erj_toolbox#1]
readme_nc_gen_20_prec.txt says "please see our processing file on Github: [https://github.com/nonpartisan-redistricting-datahub/erj-nc](https://github.com/nonpartisan-redistricting-datahub/erj-nc)" but where's that repo?

**Comment by peter-redistricting-data-hub** [comment]
I made the repo public and Spencer will have his code uploaded there shortly

**Comment by rootsmusic** [comment]
@spencer-rdh Please upload code shortly.
